name: contact_list
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flex_color_scheme: ^4.2.0
  fluttertoast: ^8.0.7
  flutter_svg: ^1.0.2
  introduction_screen: ^3.0.2
  shared_preferences: ^2.0.13
  
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
